seed: 42
data_dir: ./capture
device: cuda

data:
  _target_: dataset.CaptureDataset
  data_dir: ${data_dir}
  test_every: 8
  val_ids: null

model:
  init_num_pts: 100000
  init_extent: 3.0
  init_opa: 0.1
  init_scale: 1.0
  sh_degree: 3
  random_bkgd: false
  app_opt: false
  bilateral_grid: false

renderer:
  _target_: model.SplatRenderer
  near_plane: 0.01
  far_plane: 1.0e+10
  antialiased: false
  use_distortion: false

training:
  max_steps: 7000
  batch_size: 4
  sh_degree_interval: 1000
  ssim_lambda: 0.2
  opacity_reg: 0.0
  scale_reg: 0.0

lr:
  means: 1.6e-4
  scales: 5.0e-3
  opacities: 5.0e-2
  quats: 1.0e-3
  sh0: 2.5e-3
  shN: 1.25e-4
  app_opt: 1.0e-3
  bilateral_grid: 2.0e-3
  eps: 1.0e-15
  betas: [0.9, 0.999]
  app_opt_weight_decay: 1.0e-6

strategies:
  - _target_: gsplat.strategy.DefaultStrategy
    start_step: 0
    stop_step: ${training.max_steps}
    prune_opa: 0.005
    grow_grad2d: 0.0002
    grow_scale3d: 0.01
    grow_scale2d: 0.05
    prune_scale3d: 0.1
    prune_scale2d: 0.15
    refine_scale2d_stop_iter: 0
    refine_start_iter: 500
    refine_stop_iter: 15000
    reset_every: 3000
    refine_every: 100
    pause_refine_after_reset: 0
    absgrad: false
    revised_opacity: false
    verbose: false

loggers:
  train_metrics:
    _target_: logger.TrainMetricsLogger
    flush_every: 1000
  val_metrics:
    _target_: logger.ValMetricsLogger
    every: 1000
  val_image:
    _target_: logger.ValImageLogger
    every: 1000
  test_image:
    _target_: logger.TestImageLogger
    cameras_path: ./capture/outputs/cameras.json
    every: 1000
  checkpoint:
    _target_: logger.CheckpointLogger
    every: ${training.max_steps}
